project:
  type: book
  output-dir: _book

book:
  # book
  title: R para análisis de datos
  subtitle: Aplicación en la comunidad CLIO (Coopera, Lidera, Innova y Orienta)
  author: 
    - name: 
        given: Luis Francisco 
        family: Gomez Lopez
      affiliations:
        id: umng
        name: Universidad Militar Nueva Granada
      orcid: 0000-0002-2877-9015
  date: last-modified
  date-format: iso
  cover-image: images/front-cover.png
  downloads: [pdf]
  # favicon: pending
  site-url: https://luifrancgom.github.io/r-clio/
  repo-url: https://github.com/luifrancgom/r-clio
  issue-url: https://github.com/luifrancgom/r-clio/issues
  repo-actions: [edit, source, issue]
  sidebar: 
    logo: images/zona-clio-logo.png

  chapters:
    - index.qmd
    - preface.qmd
    - part: first_steps_r.qmd
      chapters: 
        - welcome_to_r.qmd
        - project-oriented_workflow.qmd
        - r_packages.qmd
        - how_to_code_in_r.qmd
    - part: data_visualization.qmd
      chapters: 
        - amounts.qmd
        - distributions.qmd
        - proportions.qmd
        - x-y_relationships.qmd
    - part: data_wrangling.qmd
      chapters:
        - single_table_verbs.qmd
        - two_table_verbs.qmd
    - part: data_import.qmd
      chapters:
        - r_data_serialization.qmd
        - plain_text.qmd
        - spreadsheets.qmd
        - geopackage_gpkg.qmd
    - part: data_tidy.qmd
      chapters: 
        - tidy_data.qmd
        - pivoting.qmd
        - splitting_combining.qmd
    - part: functional_programming.qmd
      chapters:
        - anonymous_functions.qmd
        - map_functions.qmd 
    - part: data_communication.qmd
    - references.qmd

bibliography: references/r-clio.bib
csl: references/apa.csl
lang: es
language: 
  crossref-nte-prefix: "Nota"
  crossref-imp-prefix: "Importante"
editor: source

format:
  html:
    theme:
      - cosmo
      - scss/custom.scss
  pdf:
    # format options
    pdf-engine: lualatex
    # colors
    linkcolor: blue
    filecolor: blue
    citecolor: blue
    urlcolor: blue
    toccolor: blue
    colorlinks: true
    # layout
    documentclass: scrbook
    papersize: a4
    # references
    link-citations: true
    link-bibliography: true
    # includes
    include-in-header: 
      - file: partials/latex/header.tex
    # rendering
    template-partials:
      - partials/latex/before-body.tex
    keep-md: false
    keep-tex: false



