# Prefacio

El presente libro tiene como objetivo introducir a la comunidad CLIO (Coopera, Lidera, Innova y Orienta) y en general a los miembros de la Universidad Militar Nueva Granada al lenguaje de programación R, el entorno integrado de desarrollo Postiron y el sistema de publicación científica y técnica de código abierto Quarto, para realizar análisis de datos.

El análisis de datos se enmarca dentro del concepto de *Ciencia de datos* (ver @fig-data-science-venn-diagram) donde se requiere un conjunto de habilidades que abarcan tener un grado de habilidades en programación, conocimientos en matemáticas y estadística así como una experticia en un determinado campo. El libro adopta una visión pragmática donde el enfoque es el desarrollo de habilidades en programación utilizando microdatos anonimizados y abiertos relacionados con los resultados del examen [Saber Pro](https://www.icfes.gov.co/evaluaciones-icfes/acerca-del-examen-saber-pro/) del grupo de competencias genéricas para programas de pregrado así como proyecciones y retroproyecciones de población a nivel nacional para Colombia elaboradas con base en los resultados del Censo Nacional de Población y Vivienda (CNPV) 2018 y actualizadas con información posterior a la pandemia de COVID-19 por parte del [Departamento Administrativo Nacional de Estadística (DANE)](https://www.dane.gov.co/index.php/estadisticas-por-tema/demografia-y-poblacion/proyecciones-de-poblacion).

El uso de este conjunto de datos se fundamenta en $2$ aspectos. En primera instancia, utilizar datos abiertos de tal manera que sean de fácil acceso. Segundo, emplear información relacionada con la Universidad Militar Nueva Granada y en particular con fenómenos que afectan el sector de educación como lo es la transición demográfica y el envejecimiento poblacional en Colombia. Debido a la hetereogeniedad respecto a los campos de experticia que puede tener la comunidad CLIO (Coopera, Lidera, Innova y Orienta) y en general los miembros de la Universidad Militar Nueva Granada se buscó aprovechar el uso de datos relacionados con la institución educativa o que afectaran de alguna manera al sector de educación superior.

![El diagrama de Venn de la ciencia de datos (Basado en [@conway_data_2010])](images/data-science-venn-diagram.png){#fig-data-science-venn-diagram fig-alt="Diagrama de Venn de tres círculos que define la Ciencia de Datos. Los círculos principales son: Habilidades de programación, Conocimiento en matemáticas y estadística, y Experticia en un campo. En las intersecciones se leen: Modelado de datos, Investigación tradicional, Análisis sin conocimiento estadístico, y en el centro, Ciencia de datos." width=65%}

El libro se construyó inicialmente utilizando las mismas herramientas que se buscan introducir (R, Positron y Quarto) donde se estructuró siguiendo las recomendaciones señaladas en [@halmos_paul_1973] respecto a escribir cada parte de forma iterativa o en espiral así como en elaborar el contenido de acuerdo a lo indicado en [@anderson_how_2009]. Además, el código fuente del libro se encuentra disponible en un [repositorio de GitHub](https://github.com/luifrancgom/r-clio) de libre acceso donde estará en constante cambio dependiendo de las necesidades que surjan y sugerencias que se reciban por parte de la comunidad CLIO (Coopera, Lidera, Innova y Orienta) y en general a los miembros de la Universidad Militar Nueva Granada.  

::: {.flushright latex="" custom-style="flushright"}
Luis Francisco Gómez López
:::